pipeline {
    agent any

    stages{
        stage("Demo"){
            steps{
                myFunction("Hello from the demo stage")
            }
        }
    }
}

def myFunction(String myText){
    echo "myText is set to: ${myText}"
}